services:
  app:
    volumes:
      - ./app:/app
    build:
      context: .
      dockerfile: Dockerfile.production
    image: valerijpapin/app_new
    env_file:
      - .env.example
    depends_on:
      db:
        condition: service_healthy
    command: ["make", "dev"]

  db:
    image: postgres:lastest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5